
# Étape 1 : Build
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG API_KEY
ENV VITE_API_KEY=$API_KEY
ENV API_KEY=$API_KEY
RUN npm run build

# Étape 2 : Serveur Node (Pas d'Nginx)
FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist
COPY --from=build /app/storage.json ./dist/
COPY --from=build /app/config.json ./dist/
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
